### ISSUE TITLE
Use ontologies to verify fields

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/calamus#7]
Currently we just use whatever a user supplies in a namespace. It'd be cool if we could optionally download a corresponding ontology and have the namespace validate that only properties that are present in the ontology are used in code.

**Comment by guptavaasu** [comment]
hey, i'm working on this issue and will try to send a fix soon

**Comment by Panaetius** [comment]
Hey there, you're welcome to pick up this issue.

Guidelines on contributing are outlined here: https://github.com/SwissDataScienceCenter/calamus/blob/master/CONTRIBUTING.rst

As mentioned there, we require outside contributors to sign the CLA found at
https://github.com/SwissDataScienceCenter/documentation/wiki/Legal-matter before we can accept contributions
